"""empty message

Revision ID: 669aeaa29b48
Revises: 0442d45dd5ce
Create Date: 2023-09-05 12:45:17.778419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669aeaa29b48'
down_revision = '0442d45dd5ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id_user'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
