"""empty message

Revision ID: ea10e7201d2e
Revises: 45a21b37e1b5
Create Date: 2023-09-01 12:44:36.736360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea10e7201d2e'
down_revision = '45a21b37e1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'vehicle', ['favourite_vehicle'], ['id'])
        batch_op.create_foreign_key(None, 'person', ['favourite_person'], ['id'])
        batch_op.create_foreign_key(None, 'planet', ['favourite_planet'], ['id'])
        batch_op.create_foreign_key(None, 'film', ['favourite_film'], ['id'])
        batch_op.create_foreign_key(None, 'starship', ['favourite_starship'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
